#!/usr/bin/env python
#-*- coding: utf-8 -*-
import socket
from multiprocessing import Pool, cpu_count
import multiprocessing
import sys
lock=multiprocessing.Lock()
def getipbysingle(beginip,endip,port):
	sk = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	sk.settimeout(1)
	#beginip='219.230.0.0'
	k=beginip.split('.')
	k0=int(k[0])
	k1=int(k[1])
	k2=int(k[2])
	k3=int(k[3])
	#endip='219.231.255.255'
	e=endip.split('.')
	e0=int(e[0])
	e1=int(e[1])
	e2=int(e[2])
	e3=int(e[3])
	c0=e0-k0
	c1=e1-k1
	c2=e2-k2
	c3=e3-k3	
	begin=beginip.split('.')
	end=endip.split('.')
	resultip=[]
	count=0
	with lock:
		for i in range(c0+1):
			kk0=k0+i		
			for j in range(c1+1):
				kk1=k1+j
				for m in range(c2+1):
					kk2=k2+m
					for h in range(c3+1):
						kk3=k3+h
						#print (str(kk0)+'.'+str(kk1)+'.'+str(kk2)+'.'+str(kk3))
						ip=(str(kk0)+'.'+str(kk1)+'.'+str(kk2)+'.'+str(kk3))
						print(ip)
						try:
						  sk.connect((ip,int(port)))
						  print ('Server port'+port+' open!')
						  count=count+1
						  resultip.append(str(kk0)+'.'+str(kk1)+'.'+str(kk2)+'.'+str(kk3)+':'+port)
						  print('已发现存在'+str(count)+'个开放'+port+'端口的主机')
						except Exception:
						  print ('Server port '+port+' not connect!')
						  print('已发现存在'+str(count)+'个开放'+port+'端口的主机')
						sk.close()	
	for ip in resultip:
		print(resultip)
def getipbymultiport(port):
	sk = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
	sk.settimeout(1)
	beginip='114.212.0.0'
	k=beginip.split('.')
	k0=int(k[0])
	k1=int(k[1])
	k2=int(k[2])
	k3=int(k[3])
	endip='134.255.255.255'
	e=endip.split('.')
	e0=int(e[0])
	e1=int(e[1])
	e2=int(e[2])
	e3=int(e[3])
	c0=e0-k0
	c1=e1-k1
	c2=e2-k2
	c3=e3-k3	
	begin=beginip.split('.')
	end=endip.split('.')
	resultip=[]
	count=0
	with lock:
		for i in range(c0):
			kk0=k0+i		
			for j in range(c1):
				kk1=k1+j
				for m in range(c2):
					kk2=k2+m
					for h in range(c3):
						kk3=k3+h
						#print (str(kk0)+'.'+str(kk1)+'.'+str(kk2)+'.'+str(kk3))
						ip=(str(kk0)+'.'+str(kk1)+'.'+str(kk2)+'.'+str(kk3))
						print(ip)
						try:
						  sk.connect((ip,int(port)))
						  print ('Server port'+port+' open!')
						  resultip.append(str(kk0)+'.'+str(kk1)+'.'+str(kk2)+'.'+str(kk3)+':'+port)
						  count=count+1
						except Exception:
						  print ('Server port '+port+' not connect!')
						sk.close()	
	for ip in resultip:
		print(resultip)
if __name__ == '__main__':
	flag=input('请选择扫描模式:1.多进程多端口端口扫描(默认扫描常见端口)，2.指定单个端口扫描(请输入数字)>>')
	if flag=='2':
		begin=input('请输入开始ip>>')
		end=input('请输入结束ip>>')
		port=input('请输入端口号>>')
		getipbysingle(begin,end,port)
	elif flag=='1':
		portlist={'21','80','8080','7001','443','445'}
		pool = Pool(processes=cpu_count())
		port=[p for p in range(1,1000)]
		pool.map(getipbymultiport,portlist)
		
